### ISSUE TITLE
Some errors and comments regarding the new website

### ISSUE THREAD

**Issue by kedos25** [manifoldfinance/web#42]
Hey @sambacha and team,

here are some errors/comments regarding the new website:

1. Old website still displayed if visited by Google search (search manifoldfinance and its the 3. result form the top).

2. The Github button throws a 404 error
![grafik](https://user-images.githubusercontent.com/80409862/159233769-0b716d49-81e3-4e3c-aab6-c56135d6a284.png)

3. The links "FOLD vault", "API", "FAQ", "SecureRPC", "Partners", "Helpdesk" in the footer links to the homepage (not sure if desired, maybe the sites are not ready for release).

4. Contact button leads to Doc page instead to contact form
![grafik](https://user-images.githubusercontent.com/80409862/159234545-399fbd18-f5a5-418f-88ad-7e4fb2a1d647.png)

5. The website is not centered if visited with mobile (iPhone XS)
![grafik](https://user-images.githubusercontent.com/80409862/159235725-a7399271-1d31-45a6-9221-12bcc107166e.png)

6. The "Governance" link in the header throws a 404 error.
![grafik](https://user-images.githubusercontent.com/80409862/159236104-902bea40-adc6-4f0e-ac70-0246fb3598be.png)

Apart from that, I did not found any bugs and the new website looks great! Awesome work :)

**Comment by dynsky** [comment]
Website ain't centered tor me too on Android

**Comment by kedos25** [comment]
Checked your fixes and mostly everything is fixed.

Three things still bugged:
- "Governance" link in the header throws a 404 error
- "Contact" button under "Data driven adoption" leads to docs page instead to contact form
- "Learn more" button under "Bespoke Opportunities" leads to contact form instead to docs page.
