### ISSUE TITLE
Lack of separators or wrong spacing 

### ISSUE THREAD

**Issue by FXLyyyy** [manifoldfinance/web#50]
Since we can't post pictures in Telegram, I've decided to do it here... I might be wrong, but that's the only way I can ask and show.

**This is the first case in which, I'm really not sure if a separator has to be there.**
<a href="https://ibb.co/jzzvsKf"><img src="https://i.ibb.co/DYYDTXW/Fold.png" alt="Fold" border="0"></a>

**Here, I'm sure that spacing is wrong.**
<a href="https://ibb.co/pJhySQY"><img src="https://i.ibb.co/syWHZC8/fold2.png" alt="fold2" border="0"></a>

**and again, no separator**
<a href="https://ibb.co/nbc0q12"><img src="https://i.ibb.co/qdsnLgG/fold3.png" alt="fold3" border="0"></a>

**Comment by sambacha** [comment]
thanks for creating this issue, I have reworked the css reseting procedure and removed the artifacts from the page, appreciate the detail!

see https://github.com/manifoldfinance/web/pull/56
