### ISSUE TITLE
Persistent errors and comments on website. 

### ISSUE THREAD

**Issue by k-above** [manifoldfinance/web#58]
**Issue 1: 'Governance' link wrong**

![Screenshot 2022-04-05 at 12 03 42](https://user-images.githubusercontent.com/100273445/161740503-19a92dd6-4394-49cb-8e46-c82847f2c0cd.png)

The “Governance” link (top right) to the forums doesn’t work because the link is wrong: 

Currently: https://forums.manifoldfinace.com/ 
Correct version: https://forums.manifoldfinance.com/ 

**Issue 2: Inconsistent capitalisation**

![Screenshot 2022-04-05 at 12 05 35](https://user-images.githubusercontent.com/100273445/161740780-32d373bb-0095-43bb-a5aa-a6876d7a6cdf.png)

Minor issue, but there is still inconsistent capitalisation of “Ethereum2” in the “Lido & Rocketpool” description. I.e., the first isn’t capitalised and the second is.

**Comment by sambacha** [comment]
closed in https://github.com/manifoldfinance/web/commit/fa7ffe75e55bb0f2d54952c5a110c4f18265fd52

thanks for reporting this
