### ISSUE TITLE
"Contact" and "Learn more" button linking to false pages

### ISSUE THREAD

**Issue by kedos25** [manifoldfinance/web#59]
**Describe the bug**
The "contact" button links to the documentation site and the "Learn more" button links to the contact form.

**Minimal Reproduction Repo / Steps to Reproduce**
Click both buttons.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80409862/162382001-fa211278-be08-4caf-b513-f5c2859f38f6.png)

**Comment by sambacha** [comment]
> **Describe the bug** The "contact" button links to the documentation site and the "Learn more" button links to the contact form.
> 
> **Minimal Reproduction Repo / Steps to Reproduce** Click both buttons.
> 
> **Screenshots** ![grafik](https://user-images.githubusercontent.com/80409862/162382001-fa211278-be08-4caf-b513-f5c2859f38f6.png)

Thanks for reporting this issue, I have fixed the redirect issue with vercel and updated alot of the links and content,
