### ISSUE TITLE
Website not correctly displayed on mobile (iOS)

### ISSUE THREAD

**Issue by kedos25** [manifoldfinance/web#60]
**Describe the bug**
The website is not correctly displayed on mobile (iOS, iPhone XS). The width is not correct and the "Governance" tab in the header is missing.

**Minimal Reproduction Repo / Steps to Reproduce**
Open the website with mobile device.

**Expected behavior**
Website should adapted to the display size of the mobile phone and "Governance" tab should be in the header.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80409862/162383100-1fcbfcd7-1f7e-4572-ada5-5d27ee3e42e4.png)

**Environment:**
iOS on iPhone XS with Brave and Safari browser.

**Comment by sambacha** [comment]
Thanks for alerting us to this, will have someone appointed to fix it

**Comment by sambacha** [comment]
This will be resolved in the next release this week

**Comment by sambacha** [comment]
this should be fixed here: https://github.com/manifoldfinance/web/commit/1422334cb045de7f8da6df7afff6b39190401970

**Comment by sambacha** [comment]
fixed in release
